# Generated by Django 2.2.5 on 2019-09-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coice',
            new_name='Choice',
        ),
    ]
